version: '3.3'
services:
  geth:
    image: ethereum/client-go
    command: --datadir=/opt/geth --dev --http -http.api="db,personal,eth,net,web3" --http.corsdomain='*'
    volumes:
      - ./geth:/opt/geth
    ports:
      - "30303:30303"       # listener
      - "30303:30303/udp"   # discovery
      - "8545:8545"         # rpc