eth:
  rpcUrl: "https://intensive-practical-sanctuary.ethereum-goerli.discover.quiknode.pro/8f6710567aa72f5950e83d7c33013a67a596283a/"
db:
  host: localhost
  port: 5432
  user: postgres
  password: example
  sslmode: disable
  name: bonotans
