// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ethereum/go-ethereum/ethclient"
	"go-bonotans/blockchain/eth"
	"go-bonotans/config"
	"log"
)

// Injectors from di.go:

func InitializeEthereum() *eth.Ethereum {
	string2 := ethRpcUrl()
	client := provideEthClient(string2)
	ethereum := eth.New(client)
	return ethereum
}

// di.go:

func ethRpcUrl() string {
	return config.Config().String("eth.rpcUrl")
}

func provideEthClient(rpcUrl string) *ethclient.Client {
	ethClient, err := ethclient.Dial(rpcUrl)
	if err != nil {
		log.Fatal(err)
	}

	return ethClient
}
